# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\crawler\nHentai_Downloader_Project\nhentai_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 380)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 631, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_url = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.input_url.setFont(font)
        self.input_url.setObjectName("input_url")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_url)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.output_path = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.output_path.setFont(font)
        self.output_path.setObjectName("output_path")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.output_path)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 190, 631, 171))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.percent = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.percent.setFont(font)
        self.percent.setObjectName("percent")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.percent)
        self.is_done = QtWidgets.QTextBrowser(self.formLayoutWidget_2)
        self.is_done.setObjectName("is_done")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.is_done)
        self.progress = QtWidgets.QTextBrowser(self.formLayoutWidget_2)
        self.progress.setObjectName("progress")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.progress)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setGeometry(QtCore.QRect(530, 100, 121, 51))
        self.ok_button.setObjectName("ok_button")
        self.filter_switch = QtWidgets.QCheckBox(Dialog)
        self.filter_switch.setGeometry(QtCore.QRect(20, 110, 181, 19))
        self.filter_switch.setChecked(True)
        self.filter_switch.setObjectName("filter_switch")
        self.chinese_switch = QtWidgets.QCheckBox(Dialog)
        self.chinese_switch.setGeometry(QtCore.QRect(20, 130, 171, 19))
        self.chinese_switch.setObjectName("chinese_switch")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "標籤網址："))
        self.label_2.setText(_translate("Dialog", "存放於："))
        self.label_3.setText(_translate("Dialog", "目前已下載"))
        self.percent.setText(_translate("Dialog", "進度"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.filter_switch.setText(_translate("Dialog", "過濾 GAY 和 GURO 本"))
        self.chinese_switch.setText(_translate("Dialog", "僅下載中文"))
